### ISSUE TITLE
GLArea demo?

### ISSUE THREAD

**Issue by brainlessbitch** [Miqueas/GTK-Examples#1]
why isn't there a GlArea demo, i'd personally find this very useful as i can't find much info on using the GlArea

**Comment by Miqueas** [comment]
That's actually a good question. I never thought about that tbh. Gotta add one later, but Idk anything about OpenGL, so... It may take a while.

**Comment by poloz-z** [comment]
@exoess uwu Josue te solicitan

**Comment by brainlessbitch** [comment]
that'd be super helpful, thank you so much

**Comment by Miqueas** [comment]
@exoess 👍

**Comment by Miqueas** [comment]
@exoess done, check commit 3798328
